CREATE TABLE IF NOT EXISTS AUTHOR (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR (50),
AGE INTEGER,
COUNTRY VARCHAR (50)
);

INSERT INTO "AUTHOR" (NAME, AGE, COUNTRY) VALUES ('Tolstoy', 40, 'Russia');

CREATE TABLE IF NOT EXISTS BOOK (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR (50),
COUNT INTEGER,
GENRE VARCHAR (50),
AUTHOR_ID BIGINT,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID)
);

INSERT INTO BOOK (NAME, COUNT, GENRE, AUTHOR_ID) VALUES ('War and Peace', 2, 'drama', 1);
