CREATE TABLE IF NOT EXISTS "AUTHOR" (
ID BIGINT auto_increment,
NAME VARCHAR (50),
AGE INTEGER,
COUNTRY VARCHAR (50),
PRIMARY KEY (ID),
);

INSERT INTO "AUTHOR" (ID, NAME, AGE, COUNTRY) VALUES (1, 'Tolstoy', 40, 'Russia');


CREATE TABLE IF NOT EXISTS "BOOK" (
ID BIGINT auto_increment,
NAME VARCHAR (50),
COUNT INTEGER,
GENRE VARCHAR (50),
AUTHOR_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (AUTHOR_ID) REFERENCES "AUTHOR" (ID)
);

INSERT INTO "BOOK" (ID, NAME, COUNT, GENRE, AUTHOR_ID) VALUES (1, 'War and Peace', 2, 'drama', 1);
